matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.4
      before_script:
        - cd webapi
      script: dotnet build
    - language: node_js
      node_js: 8
      cache:
      directories:
        - node_modules
      before_script:
        - cd client
        - npm i g @angular/cli
      script: npm run build
      after_success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=lrvedeler/sykkeldeleringen
        - export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH ; fi`
        - docker build -f Dockerfile -t $REPO:$COMMIT .
        - docker tag $REPO:$COMMIT $REPO:$TAG
        - docker tag $REPO:$COMMIT $REPO:travis-$TRAVIS_BUILD_NUMBER
        - docker push $REPO