matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.4
      before_script:
        - cd webapi
      script: dotnet build
    - language: node_js
      node_js: 8
      cache:
      directories:
        - node_modules
      before_script:
        - cd client
        - npm i g @angular/cli
      script: npm run build
      after_success:
        - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
        - export REPO=lrvedeler/sykkeldeleringen
        - docker build -f Dockerfile .
        - docker push $REPO