matrix:
  include:
  - language: csharp
    mono: none
    dotnet: 2.1.4
    before_script:
    - cd webapi
    - sed -e "s/@password/$DB_PASSWORD/g" -e "s/@jwtSecret/$JWT_SECRET/g" webapi/appsettings.json
    - dotnet sln webapi.sln remove docker-compose.dcproj
    script: dotnet build webapi.sln
    after_success:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" https://sdrcontainerreg.azurecr.io
    - export REPO=sdrcontainerreg.azurecr.io/webapi
    - docker build -t $REPO:latest -f dockerfile .
    - docker push "$REPO"
  - language: node_js
    node_js: 8
    cache: 
    directories:
    - node_modules
    before_script:
    - cd client
    - npm i g @angular/cli
    script: npm run build
    after_success:
    - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS" https://sdrcontainerreg.azurecr.io
    - export REPO=sdrcontainerreg.azurecr.io/client
    - docker build -t $REPO:latest -f dockerfile .
    - docker push "$REPO"
