matrix:
  include:
    - language: csharp
    before_script:
      - cd webapi
    solution: webapi.sln
  include:
    - language: node_js
    node_js: 8
    cache:
    directories:
    - node_modules
    before_script:
      - cd client
    script: npm run build