matrix:
  include:
    - language: csharp
      mono: none
      dotnet: 2.1.4
      solution: webapi/webapi.sln
      script: dotnet build
    - language: node_js
      node_js: 8
      cache:
      directories:
        - node_modules
      before_script:
        - cd client
        - npm i g @angular/cli
      script: npm run build