matrix:
  include:
    - language: csharp
      solution: webapi/webapi.sln
    - language: node_js
      node_js: 8
      cache:
      directories:
        - node_modules
      before_script:
        - cd client
        - npm i g @angular/cli
      script: npm run build